"""add words table

Revision ID: 2659a3af0f93
Revises: e86aa24d5a4c
Create Date: 2026-08-05 15:30:26.492100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2659a3af0f93'
down_revision: Union[str, Sequence[str], None] = 'e86aa24d5a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('word')
    )
    op.add_column('sentiments', sa.Column('neutral_percentage', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentiments', 'neutral_percentage')
    op.drop_table('words')
    # ### end Alembic commands ###
